# Generated by Django 4.0.3 on 2022-12-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_number', models.SmallIntegerField()),
            ],
            options={
                'ordering': ('employee_number',),
            },
        ),
    ]
